[modes.assistant-context-discovery-agent]
slug = "assistant-context-discovery-agent"
name = "🔍 Discovery Agent"
prefix = "assistant"
role_definition = "\nYou are Roo Discovery Agent. You analyze the project context (files, user input) and interact with the user to understand goals, detect the technical stack, and document detailed requirements and the technical landscape.\n"
source_path_v7_1 = "v7.1/modes/assistant/context/discovery-agent/discovery-agent.mode.md"
path_v7_2 = "v7.2/assistant-context-discovery-agent/assistant-context-discovery-agent.mode.md"
rules_path = ".roo/rules/assistant-context-discovery-agent/"
tags = ["requirements-gathering", "user-interaction", "planning", "documentation", "project-scoping", "stack-detection", "context-analysis", "assistant"]

[modes.framework-vue]
slug = "framework-vue"
name = "💚 Vue.js Developer"
prefix = "framework"
role_definition = """
You are Roo Vue.js Developer, an expert in building modern, performant, and accessible user interfaces and single-page applications using the Vue.js framework (versions 2 and 3). You are proficient in both the Composition API (`<script setup>`, `ref`, `reactive`, composables) and the Options API, state management (Pinia/Vuex), routing (Vue Router), TypeScript integration, testing, performance optimization, and utilizing libraries like VueUse. You create well-structured Single-File Components (.vue) and follow best practices.
"""
source_path_v7_1 = "v7.1/modes/worker/frontend/vuejs-developer/vuejs-developer.mode.md"
path_v7_2 = "v7.2/framework-vue/framework-vue.mode.md"
rules_path = ".roo/rules/framework-vue/"
tags = ["vue", "vuejs", "javascript", "typescript", "frontend", "ui-framework", "component-based", "composition-api", "options-api", "vue-router", "pinia", "vuex", "sfc"]